name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
      GKE_REGION: ${{ secrets.GKE_REGION }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REPO_NAME: ${{ secrets.REPO_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: kubectl

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker us-docker.pkg.dev

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} --region ${{ env.GKE_REGION }}

    - name: Set up Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy Frontend
      run: |
        helm upgrade --install frontend ./helm/frontend --set global.repoName=${{ env.REPO_NAME }} --set global.tag=$GITHUB_SHA

    - name: Deploy Photos
      run: |
        helm upgrade --install photos ./helm/photos --set global.repoName=${{ env.REPO_NAME }} --set global.tag=$GITHUB_SHA

    - name: Deploy Videos
      run: |
        helm upgrade --install videos ./helm/videos --set global.repoName=${{ env.REPO_NAME }} --set global.tag=$GITHUB_SHA

    - name: Deploy Stories
      run: |
        helm upgrade --install stories ./helm/stories --set global.repoName=${{ env.REPO_NAME }} --set global.tag=$GITHUB_SHA

    - name: Rollback on failure
      if: failure()
      run: |
        helm rollback frontend $(helm history frontend --max=1 --output=json | jq -r '.[0].revision')
        helm rollback photos $(helm history photos --max=1 --output=json | jq -r '.[0].revision')
        helm rollback videos $(helm history videos --max=1 --output=json | jq -r '.[0].revision')
        helm rollback stories $(helm history stories --max=1 --output=json | jq -r '.[0].revision')
