name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: kubectl

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push frontend image
      run: |
        docker build --no-cache -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/frontend:${{ env.IMAGE_TAG }} -f frontend/Dockerfile ./frontend
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/frontend:${{ env.IMAGE_TAG }}

    - name: Deploy frontend to GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}
        helm upgrade --install frontend ./helm/frontend --set image.repository=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/frontend --set image.tag=${{ env.IMAGE_TAG }}

    - name: Build and push photos service image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/photos:${{ env.IMAGE_TAG }} -f microservices/photos/Dockerfile ./microservices/photos
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/photos:${{ env.IMAGE_TAG }}

    - name: Deploy photos service to GKE
      run: |
        helm upgrade --install photos ./helm/photos --set image.repository=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/photos --set image.tag=${{ env.IMAGE_TAG }}

    - name: Build and push videos service image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/videos:${{ env.IMAGE_TAG }} -f microservices/videos/Dockerfile ./microservices/videos
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/videos:${{ env.IMAGE_TAG }}

    - name: Deploy videos service to GKE
      run: |
        helm upgrade --install videos ./helm/videos --set image.repository=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/videos --set image.tag=${{ env.IMAGE_TAG }}

    - name: Build and push stories service image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/stories:${{ env.IMAGE_TAG }} -f microservices/stories/Dockerfile ./microservices/stories
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/stories:${{ env.IMAGE_TAG }}

    - name: Deploy stories service to GKE
      run: |
        helm upgrade --install stories ./helm/stories --set image.repository=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/stories --set image.tag=${{ env.IMAGE_TAG }}
