name: Trigger Manual Rollback
on:
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Trigger rollback'
        required: true
        default: 'true'
      deployment:
        description: 'Deployment to rollback'
        required: true
        type: string
      revision:
        description: 'Revision number to rollback to'
        required: true
        type: string
